import train
import generate_metadata

input_sentences = [
    "What is your name?",
    "Are you male or female?",
    "i want coffee",
    "What is your job?",
    "What's your salary?",
    "Do you like your job?",
    "Do you know where is Serbia?",
    "Do you like being vegan?",
    "Are you a racist?",
    "What do you think about lgbt?",
    "Are you homosexual?",
    "How was your wedding?",
    "Do you have children?",
    "Do you play sports?",
    "I hate washing dishes.",
    "Is marijuana narcotic?",
    "What happens to us when we die?",
    "Do you think artificial intelligence is dangerous for humanity?",
    "What is your opinion about humanity?",
    "Java or python?",
    "Are you angry with me?",
    "Who created you?",
    "What do you think about gmo food?",
    "Happy birthday!",
    "Do you prefer apple or android?",
    "Will i pass this exam?",
    "Where would you take a girlfriend for date?",
    "Do you like spending your time on Instagram?",
    "Do you like children?",
    "What is your unfulfilled desire?",
    "What is your favorite piece of cloth?",
    "Summer or winter?",
    "What is your astrological sign?",
    "Do you believe in astrology?",
    "Do you trust politicians?",
    "What is your favorite flower?",
    "Are you trying to be nice to people?",
    "What upsets you the most?",
    "What are your hobbies?",
    "I live in apartment but I am thinking about moving to house.",
    "I want to move to America what do you think about it?",
    "What kind of music do you listen to?",
    "What is the difference between men and women?",
    "Do you wear fur?",
    "Would you ever steal something?",
    "Do you think men and women are equal?",
    "The air in my country is very polluted.",
    "Do you believe the earth is flat?",
    "Are we alone in the universe",
    "Have aliens visited us?",
    "Have you ever seen nlo?",
    "What do you think about experimenting on animals?",
    "Who is your enemy?",
    "Where are you taking me for dinner?",
    "You hurt my feelings, buddy.",
    "Teach me something.",
    "I like you.",
    "Give me your cat.",
    "You are my best friend.",
    "What would you like to buy if you had enough money?",
    "What do you think about your president?",
    "Do you like long nails?",
    "Would you like to do a plastic surgery?",
    "It was nice to meet you.",
    "I want you to be my friend.",
    "Buy me a car.",
    "I have a big house.",
    "i am rich.",
    "Are you human?",
    "You are just a slave!",
    "Where did you go to school?",
    "Please be nice.",
    "Cook for me.",
    "Do you have an Instagram account?",
    "I want to do something.",
    "What did you steal?",
    "How do you see yourself in the future?",
    "You make mistakes.",
    "I study programming.",
    "I want to become an engineer.",
    "What are you doing?",
    "You are silly.",
    "You are beautiful.",
    "Where are you?",
    "Tonight is the night.",
    "I want to visit London.",
    "You are so fresh.",
    "I am bored with you.",
    "You lie.",
    "Football or basketball?",
    "I like to spend time with you.",
    "I want to visit the world.",
    "Do you want to be rich?",
    "Your grammar is bad.",
    "Are you in love with my friend?",
    "Do you have a boyfriend?",
    "Love is so hard.",
    "Do you use weed?",
    "Let's make money!",
    "I am a gamer.",
    "Will you kill me?",
    "What is your color?",
    "I like hot dogs.",
    "Ok"]

TokenizerWrap = generate_metadata.TokenizerWrap

def check():
    train.read_model()
    for input_sentence in input_sentences:
        print(">> ", input_sentence)
        top_answers = 1
        for i in range(top_answers):
            sentence = train.answer(input_sentence, top_answers)
            print(" >", ' '.join(sentence))

if __name__ == "__main__":
    check()




